# Generated by Django 5.0.6 on 2024-07-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_contact_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='country',
            field=models.CharField(default='India', max_length=30),
        ),
    ]
